name: Build bazel
on:
  push:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master

      - name: Bazel build code
        run: bazel build //...:all

      - name: Test simple operation
        run: bazel test //test:simple_operation_test

      - name: Test compaction
        run: bazel test //test:compaction_trigger_test

      - name: Test startup
        run: bazel test //test:wal_recovery_test

      - name: Test data block
        run: bazel test //test:data_block_integration_test

      - name: Test database lock
        run: bazel test //test:database_lock_test

      - name: Test manifest
        run: bazel test //test:manifest_activity_test